# Generated by Django 4.2.20 on 2025-03-10 10:25

import book.models.code
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0002_book_isbn_book_published_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('code_number', models.CharField(max_length=200)),
                ('expired_date', models.DateTimeField(default=book.models.code.code_time)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
